import {useEffect,useState} from "react";
import {Link,Navigate,Route,Routes,useNavigate} from "react-router-dom";
const API_URL=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
async function api(path,options={}){const response=await fetch(`${API_URL}${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Request failed");return data}
function Navbar({user,onLogout}){return <nav><Link className="brand" to="/">Task 3 Auth</Link><div>{user?<><Link to="/dashboard">Dashboard</Link><button onClick={onLogout}>Logout</button></>:<><Link to="/login">Login</Link><Link to="/register">Sign Up</Link></>}</div></nav>}
function Protected({user,children}){return user?children:<Navigate to="/login" replace/>}
function Auth({mode,onLogin}){const isLogin=mode==="login";const nav=useNavigate();const[form,setForm]=useState(isLogin?{email:"",password:""}:{name:"",email:"",password:""});const[error,setError]=useState("");const[loading,setLoading]=useState(false);async function submit(e){e.preventDefault();setError("");setLoading(true);try{const data=await api(`/auth/${isLogin?"login":"register"}`,{method:"POST",body:JSON.stringify(form)});onLogin(data.user);nav("/dashboard")}catch(e){setError(e.message)}finally{setLoading(false)}}return <section className="auth"><form onSubmit={submit}><h1>{isLogin?"Login":"Create account"}</h1><p>{isLogin?"Sign in to access the protected dashboard.":"Create an account with a securely hashed password."}</p>{error&&<div className="error">{error}</div>}{!isLogin&&<label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label>}<label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<input type="password" minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><button className="primary" disabled={loading}>{loading?(isLogin?"Signing in...":"Creating..."):(isLogin?"Login":"Sign Up")}</button><p>{isLogin?<>No account? <Link to="/register">Sign Up</Link></>:<>Already registered? <Link to="/login">Login</Link></>}</p></form></section>}
function Dashboard({user,onLogout}){const[data,setData]=useState(null);const[error,setError]=useState("");useEffect(()=>{api("/protected").then(setData).catch(e=>setError(e.message))},[]);return <section><div className="hero"><div><span>PROTECTED ROUTE</span><h1>Welcome, {user.name}!</h1><p>Your JWT-protected React page is working.</p></div><button className="primary" onClick={onLogout}>Logout</button></div><div className="cards"><article><h2>Authenticated User</h2><p><b>Name:</b> {user.name}</p><p><b>Email:</b> {user.email}</p></article><article><h2>Protected API</h2>{error?<p className="error">{error}</p>:data?<><p>{data.message}</p><b className="success">JWT verified successfully ✓</b></>:<p>Loading...</p>}</article></div><article className="security"><h2>Security Notes</h2><ul><li>Password is stored as a bcrypt hash.</li><li>JWT is stored in an HTTP-only cookie.</li><li>Protected routes verify the JWT.</li><li>Logout clears the cookie.</li></ul></article></section>}
function Home({user}){return <section className="hero home"><span>ALFIDO TECH • TASK 3</span><h1>Authentication & Protected Routes</h1><p>React + Node.js + Express + MongoDB + bcrypt + JWT</p>{user?<Link className="primary link" to="/dashboard">Open Dashboard</Link>:<Link className="primary link" to="/login">Get Started</Link>}</section>}
export default function App(){const[user,setUser]=useState(null);const[checking,setChecking]=useState(true);useEffect(()=>{api("/auth/me").then(d=>setUser(d.user)).catch(()=>setUser(null)).finally(()=>setChecking(false))},[]);async function logout(){try{await api("/auth/logout",{method:"POST"})}finally{setUser(null)}}if(checking)return <div className="loading">Checking authentication...</div>;return <><Navbar user={user} onLogout={logout}/><main><Routes><Route path="/" element={<Home user={user}/>}/><Route path="/login" element={user?<Navigate to="/dashboard"/>:<Auth mode="login" onLogin={setUser}/>}/><Route path="/register" element={user?<Navigate to="/dashboard"/>:<Auth mode="register" onLogin={setUser}/>}/><Route path="/dashboard" element={<Protected user={user}><Dashboard user={user} onLogout={logout}/></Protected>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></main></>}
